### ISSUE TITLE
How to chage the album art too

### ISSUE THREAD

**Issue by sksar** [alashow/music#11]
I want to create a custom function which will chage the album art too..
i see that this code is doing a force download
`function forceDownload($filePath, $fileName) {
  logDownload("$filePath $fileName");
  checkIsBadMp3($filePath);
  header("Cache-Control: private");
  header("Content-Description: File Transfer");
  header("Content-Disposition: attachment; filename=\"" . sanitize($fileName, false, false) . ".mp3\"");
  header("Content-Type: audio/mpeg");
  header("Content-length: " . filesize($filePath));
  readfile($filePath);
}`

first i wanna know how much does this costs in performance of the server..

also i like this function because it directly outputs the file... 
but i want to change it so that `the file is directly outputted without downloading`
also in the mean time i wanna change the album art and other id 3 tags and then output it to the user..

**Comment by alashow** [comment]
You can change anything in mp3 before calculating file size for header and `readfile()` function. I suggest you to do it just after `checkIsBadMp3()`.

Don't know exactly, but changing local file's information should not take much power. It will take time if you get album art from third party source. But not if you want custom fixed album art for all mp3's. That will be fast & not memory consuming.

I didn't understand what do you mean by `the file is directly outputted without downloading`. You want to stream mp3 so you can play it in browser? 
If yes, in that case use `stream()` function instead of `forceDownload()`.

**Comment by sksar** [comment]
What i wanted to mean is that, when i get a song's url. i don't wanna download it, instead i will directly get it into a variable through file_get_contents and echo it to the user. But before echoing i will make some changes to the variable such the the id3 tags are set properly including the album art.. while searching the web i came up across this php script on the page [http://php.net/manual/en/ref.id3.php#71191](http://php.net/manual/en/ref.id3.php#71191)
there i found this code

```
<?php 
define(_Title,"TIT2"); 
define(_Artist,"TPE1"); 
define(_Group,"TPE2"); 
define(_Album,"TALB"); 
define(_Genre,"TCON"); 
define(_TrackNo,"TRCK"); 
define(_Year,"TYER"); 
$frames = array(_Album=>"The Ultimate Experience", 
  _TrackNo=>"1", 
  _Title=>"All along the watchtower", 
  _Artist=>"Jimi Hendrix", 
  _Group=>"", 
  _Year=>"19xx", 
  _Genre=>"Rock"); 

#.......................................... 
#       WRITE ID3 TAGS (Write MP3 [v1, v2] 
#.......................................... 
function writeTags($mp3) { 
    $fl = file_get_contents($mp3); 
    $Header = substr($fl,0,10); 
    $tagLen = calcDecTagLen(substr($Header,6,4),$tagLen); 
    $music = substr($fl,$tagLen+10,-128); 
    # Can use input Header for output but you may 
    # wish to change the output filename for testing 
        $tagLen = 1024; # or whatever you like >your actual 
        $Header = substr($Header,0,6).setHexTagLen($tagLen); 
        file_put_contents($mp3,mkV2Tag($Header,$tagLen).$music.mkV1Tag()); 
} 
#   Create the V2 tag 
function mkV2Tag($Hdr,$tagLen) { 
    Global $frames; 
    $null = chr(0); 
    $nl3 = $null.$null.$null;            # 0 bytes for flags and encoding 
    $out = ""; 
    foreach($frames as $ky=>$val) { 
        $n=strlen($val)+1; 
        $out.= $ky.mkFrmLen($n).$nl3.$val; 
        } 
    return $Hdr.str_pad($out,$tagLen,$null); 
    } 
#    Calculate Tag Length from bytes 6-10 of existing header 
function calcDecTagLen($word) { 
    $m = 1; 
    $int = 0; 
    for ($i=strlen($word)-1;$i>-1;$i--) { 
        $int +=$m*ord($word[$i]); 
        $m=$m*128; 
        } 
    return $int; 
    } 
#    Make the 4 byte frame length value for the V2tag 
function mkFrmLen($int) { 
    $hx = ""; 
    while ($int>0) { 
        $n = $int % 256; 
        $hx = chr($n).$hx; 
        $int=floor($int/256); 
        } 
    return str_pad($hx,4,chr(0),STR_PAD_LEFT); 
    } 
#    Create the 128 byte V1 tag 
function mkV1Tag() { 
    Global $frames; 
    $tagOut = "TAG". 
        adj($frames[_Title]). 
        adj($frames[_Artist]). 
        adj($frames[_Album]). 
        str_pad($frames[_Year],4). 
        str_pad(" ",29," "). 
        chr($frames[_TrackNo]). 
        chr($n); 
    return $tagOut; 
    } 
#    Pad the header to 30 characters 
function adj($str) { 
    return substr(str_pad($str,30,chr(0)),0,30); 
    } 
    
#     This is a simple example for an mp3 in current folder    
    writeTags("01-Cognac Blues.mp3"); 
?> 

The setHexTagLen can be figured out from the calcDecTagLen but here's some sample code. 

<?php 
function setHexTagLen($int) { 
    $n = pow(128,3); 
    $intVar = $int; 
    $m = ""; 
    for ($i=0;$i<4;$i++) { 
        $m .= chr(floor($intVar/$n)); 
        $intVar = $intVar % $n; 
        $n=$n/128; 
        } 
    return $m; 
} 
?>
```

I am happy to get the code cause it has nearly solved my problem, in the function write tags instead of doing `file_put_contents` i will just echo it to the user. But one thing is still not clear to me which is how to put in the album art in it. I googled about `ID3 tags` and i found out that album art is to be specified at the `beigning of the file` that is I`D3 version 2 tags`. So i think there is something to mess with the `mkV2Tag()` function. 

Can you figure it out how to do it?

**Comment by alashow** [comment]
Check out this answer: http://stackoverflow.com/a/23336679/2897341

Or alternatively, there are faster and easier solution. You can use PHP's `exec()` function to execute command line applications like [this one](http://eyed3.nicfit.net/).

**Comment by sksar** [comment]
The code you suggested uses an class which in turn uses getid3 class of php.. which is not what i want... it is becoming more complex if i am using classes.. The function i wrote above is better than any other tag modifier i have ever seen... So i would prefer to use it. but can you just find out some ways in which the id3 v2 tags can be added an image with
