### ISSUE TITLE
VK API tokens

### ISSUE THREAD

**Issue by sksar** [alashow/music#12]
I see that you use a token. I tried to get one from the vk developer's website after creating a app. but i am not able to get it.

But i have a few question... I am creating a real commercial level free music downloads website, so there will be a lot of searches. so i need to get my own token. and also i wanna know how long is a token valid.

Basically what i want to do is to make the website so that it needs less maintenance .
If the token is valid for many days. then its okay.. 
The target is to allow public to download music without the need to have a vk account. and authorise. it was better if vk audio api was available for public use but i need a workaround which is more foolproof..

So what rough edges do i have in there.. also how can i get a  valid token..

**Comment by alashow** [comment]
> I wanna know how long is a token valid.

I think, tokens don't have expire time.
I used to have a lot of flood control errors, which is depends on user. If you create a lot of tokens from same user, it doesn't matter: if one of them give flood control error, all tokens will give too.
So better create 1 token from different users.
Learn more about authorization at: https://new.vk.com/dev/main
Errors: https://new.vk.com/dev/errors.

>Also how can i get a valid token.

Instructions for getting token is on [wiki page](https://github.com/alashow/music/wiki#how-to-get-your-own-token).

**Comment by sksar** [comment]
For suppose i have managed only one user.. So will multiple apps would help. So in that way i can get as many as tokens... Also if i have more users i can get more.. I asked vk support team a question. lets see what they reply. 

And ya i got an api key using my vk account.. but i want more can you give me one for your account? App id is 5530361..

**Comment by alashow** [comment]
> And ya i got an API key using my VK account.. but i want more can you give me one for your account? My App id is 5530361.. Send me soumyakantisar@gmail.com

Sorry, I can't do that. 

> Also one more question that, if the audio.search is just a public usage API (means no need of user's data modification like the audio.delete) then why does it require a token? I know its a matter of heated discussion but still is it not like the google search API, which doesn't require tokens..? Do you have anything to say about it?

I don't know why VK developers made it non-public. https://vk.com/dev/audio.search
