### ISSUE TITLE
Big refactor: convert to Node.js project.

### ISSUE THREAD

**Issue by alashow** [alashow/music#16]
Hello everyone.

I was planning this for a while. Couldn't find time to learn Node.js itself. Opening this issue for to create task list and ask for help.

Converting to Node.js will have several advantages:
1. Project will be more modern, using modern web technology. Beautiful server side code (curently divided to simple php files).
2. ... (at this point, don't know what to write. I thought it has more advantages. I just feel that it's good :) Will be updated.)
- [ ] Learn more about Node.js, express.js, bower, npm.
- [ ] ... (Will be updated)

Any suggestions, contributions are very welcome! If you think you can help me with converting it, please contact me at me@alashov.com!

Thank you.
Best Regards, Alashov.

**Comment by Porco-Rosso** [comment]
Although I love node.js, personally, I don't see the point in moving to  Node.js for this project.
The complexity will be higher, install and deployment will be tougher, and I fail to see many benefits. Maybe some sort of plugins, or easier feature integration?
Nevertheless, best of luck!

**Comment by alashow** [comment]
Thank you for response Porco- Rosso!

After reading docs and tutorials about Node.js, I agree with you on that.  Couldn't find other benefits for now.

Do you mean plugins & feature integration for datmusic? That sounds awesome. Any ideas for implementation, plugin examples?

I will keep this issue open for a while. In case me or someone will have ideas worth for converting.

**Comment by Porco-Rosso** [comment]
I did mean plugins and features for datmusic.
I don't have any great ideas, but maybe something like:

- Music visualizers
- Audio effects/conversion
- Metadata fetching/correcting and embedding (artwork, artists etc)
- Airplay/chromecast integration
- Storage backend

Personally on the last point I have been dreaming of a Spotify style music player that uses [IPFS](https://ipfs.io/) as a backend. Bootstrapping it from vk sourced content would work well.

**Comment by alashow** [comment]
Implemented simple telegram bot: https://github.com/alashow/datmusicbot
[@datmusicbot](https://telegram.me/datmusicbot)
