### ISSUE TITLE
redirect_uri issue

### ISSUE THREAD

**Issue by oarsman** [alashow/music#17]
Hello,

I updated my redirect URLs on api settings page but i got this error from vk;

{"error":"invalid_request","error_description":"redirect_uri is incorrect, check application redirect uri in the settings page"}

i am testing your script on; [https://www.mp3ox.com/inc/music-master/index.php](https://www.mp3ox.com/inc/music-master/index.php)

upadted the lines on **app.js & app.min.js**;

**app.js:**
 appUrl: window.location.protocol + "//www.mp3ox.com/inc/music-master/",
 downloadServerUrl: window.location.protocol + "//www.mp3ox.com/inc/music-master/",

**app.min.js:**
g={title:"mp3ox",appUrl:window.location.protocol+"//www.mp3ox.com/inc/music-master/",downloadServerUrl:window.location.protocol+"//www.mp3ox.com/inc/music-master/",proxyMode:!0,proxyDownload:!0,captchaProxy:!

can you please help me with this?

thanks!

**Comment by alashow** [comment]
You don't need to enable OpenAPI. Disable it, then try again.
