### ISSUE TITLE
Parse syntax error

### ISSUE THREAD

**Issue by nibreh** [alashow/music#18]
Hello Alashow

I see there is new updates to music. It's working fine for me with [Commits on Mar 1, 2016 - metas](https://github.com/alashow/music/tree/0e0ede698e75218ed0e97042665a696d8b134b76), I'm using it with no problems

After that, with recent commits, I've got some problems to **play song on click** when proxyMode & proxyDownload are enabled.

Furthermore, with `download.php` I got this:
`Parse error: syntax error, unexpected end of file in /www/download.php on line 251`

Problem seems to come from line 61 to 90. My PHP Version is **5.6.24**

See you & enjoy music
/ juh

**Comment by alashow** [comment]
Can you try enabling warnings?

My server's PHP version is 5.6.23 and have no any problems with syntax.

**Comment by nibreh** [comment]
I got the parse error syntax on my web hosting.

Now I testing on localhost with apache+php5.6.24 debian jessie, and I got the same error with syntax in download.php

When proxyMode is enabled I got this too in error.log (give me NETWORK error!):
`PHP Notice:  Undefined index: tokenIndex in helper.php on line 23`

By enable warnings, did you mean `error-reporting` in php.ini ? It's E_ALL. 
Sorry but I'm not very with php and server ;)

**Comment by alashow** [comment]
I think I know what is the problem.

On line [95](https://github.com/alashow/music/blob/master/download.php#L85) there is short open tag. `<?` instead of `<?php`. You need to enable `short_open_tag on your `php.ini`.

http://php.net/manual/en/ini.core.php#ini.short-open-tag
http://stackoverflow.com/questions/2185320/how-to-enable-php-short-tags

**Comment by nibreh** [comment]
Fixed ! `download.php` is working fine right now.

Thanks for your time, the trick and the links !

Cheers / juh
