### ISSUE TITLE
Help with local installation

### ISSUE THREAD

**Issue by drpoup** [alashow/music#2]
Hi, how can I run my own version of this?
- By this I mean how can I use my own accessToken, and host it on my own server?

Great tool by the way!

**Comment by drpoup** [comment]
Sorry to reopen this thread, but I've been struggling to get a new, working access token.

using an app I created I can successfully get a token:
> https://oauth.vk.com/authorize?client_id=4715793&scope=audio,offline&redirect_uri=https://oauth.vk.com/blank.html&response_type=token

Result: 
> 79098f9d02eeb3178aadecc95070dce0e88299c7e7cbda42e4b31caa2fdf4f43095564a900db388b030f6

But sadly, no matter what permissions, or app settings I tried none of the codes work, and I keep getting an:
> Error: Internal server error: could not get application

How did you get the original access token? I can't help but find it's longer then any of the ones I have generated.

Thank you!

**Comment by alashow** [comment]
just now i pushed new commit. In https://github.com/alashow/music/blob/master/js/app.js have documentation about it

**Comment by drpoup** [comment]
Thanks for the quick response, I got it now. I shouldn't have been so stupid and looked into the Secure Key being included.

I've worked on a few features for the app myself, such as a dynamic playlist feature and download buttons. I'll post a fork sometime soon.
