### ISSUE TITLE
Регулировка громкости плеера

### ISSUE THREAD

**Issue by rikishi0071** [alashow/music#20]
Здравствуйте, В веб-плеере https://datmusic.xyz отсутствует регулировка громкости программным ползунком, приходится увеличивать/уменьшать громкость системными средствами! Можно как-нибудь сделать регулировку громкости встроенную в плеер? Спасибо!

**Comment by alashow** [comment]
Привет.

Я не добавил регулятор громкости, чтобы сохранить веб-плеер пользовательский интерфейс минимальным.

**Comment by spakks** [comment]
Aloshow,

              Сердечное спасибо за что делает этот скрипт. Следуйте всем инструкциям.
Любая ошибка, что игра не работает. Я хотел бы помочь. Проблема в API? spakks.com
