### ISSUE TITLE
New API

### ISSUE THREAD

**Issue by alashow** [alashow/music#23]
Hello guys!

Good news! Yesterday I started writing new api/parser for VK website.

https://github.com/alashow/datmusic-api

I have removed php side from this repo and left only javascript side.

**Downsides of new API**
- Currently, there is no sorting or choosing performer only options (m.vk.com/audio has no options for that, need to update parse to use vk.com/audio)
- Mp3 download links are not fixed. Download/stream links will only work while it's API cache (24 hr)

But anyways, it works. Better than nothing.

API needs some more work to be stable. 

PR's are very welcome!

Thank you for using datmusic!

**Comment by Porco-Rosso** [comment]
Thank you so much for this! I might be able to keep my project alive thanks to you! 
Btw I don't understand exactly how a finally formed link should look.

https://api.datmusic.xyz/{search_hash}{audio_hash}/{}
to this?
https://api.datmusic.xyz/21fe04ff/8f88088a

If so you are missing a forward slash between the search and audio hashes in your readme.

Thanks for the great work!

**Comment by alashow** [comment]
Yes, it needs slash between them.

Anyways, you don't "parse" download links from id like before, full links will be in audio object in json.

**Comment by olegcom** [comment]
After downloading the music folder and all the files in the site root.
Due to with the transition to https://api.datmusic.xyz/.
Do I need to change something else?
Because I get the message
Network error!

**Comment by alashow** [comment]
@olegcom Hey.

You are not supposed to use https://api.datmusic.xyz as your backend. You need to deploy your own server for your application/website (https://github.com/alashow/datmusic-api).

Network error is probably because of [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS). As for https://api.datmusic.xyz CORS only enabled for datmusic.xyz.
When you deploy your own api, add your frontend domain to [this](https://github.com/alashow/datmusic-api/blob/master/config/cors.php#L14) list.
