### ISSUE TITLE
The recoded/original bitrate and file size are inverted

### ISSUE THREAD

**Issue by JanPokorny** [alashow/music#24]
This is pretty confusing:
![image](https://cloud.githubusercontent.com/assets/4580066/21614825/6892ad9e-d1db-11e6-9fa6-00fe3ff6a6fe.png)
Anyway, keep up the good work!
EDIT: Not even mentioning one says `kbit` and the other `kbps`

**Comment by alashow** [comment]
Hey.

I don't know why I did it "kbit" but I can remember why did I invert: to distinguish calculated value (guessing how big will be converted size and predicted bitrate of the original) and exact value.

Do people really find it confusing? I should change it if they are. Also, I need to remove `~` sign from both or only from original bitrate prediction, it's almost exact number anyways.

**Comment by JanPokorny** [comment]
I can't speak for others, but I find it confusing and believe others do too. I'm for unifying the bitrate/size order and removing the ~ sign -- that would make the dropdown more readable.
Here's a quick mockup:
![image](https://cloud.githubusercontent.com/assets/4580066/21615705/fa790818-d1de-11e6-8eda-55638e4160bb.png)
