### ISSUE TITLE
UI drops out first search result

### ISSUE THREAD

**Issue by JanPokorny** [alashow/music#26]
The result of calling `https://api.datmusic.xyz/search?q=Beatles`:

```json
{"status":"ok","data":[{"artist":"The Beatles","title":"Twist and Shout ","duration":156,"download":"https:\/\/api.datmusic.xyz\/0a6902c1\/e61f424c","stream":"https:\/\/api.datmusic.xyz\/stream\/0a6902c1\/e61f424c"},{"artist":"The Beatles","title":"Hello, Goodbye","duration":207,"download":"https:\/\/api.datmusic.xyz\/0a6902c1\/6e734026","stream":"https:\/\/api.datmusic.xyz\/stream\/0a6902c1\/6e734026"},{"artist":"Rae Sremmurd","title":"Black Beatles (MAKJ Remix)","duration":169,"download":"https:\/\/api.datmusic.xyz\/0a6902c1\/6f4d40d2","stream":"https:\/\/api.datmusic.xyz\/stream\/0a6902c1\/6f4d40d2"},...
```

But the same search on the web version yields:
![image](https://cloud.githubusercontent.com/assets/4580066/21617504/bb7cb53a-d1e6-11e6-8c3c-cdae437a23ff.png)
Twist and Shout is missing. This can especially hurt some songs that have only one instance on VK.com.

**Comment by alashow** [comment]
Forget to change start index to 0 when moving to new API. In the old API, the 1 item (`0`th index)  total count.

Thank you for reporting!
