### ISSUE TITLE
Captcha Needed

### ISSUE THREAD

**Issue by drpoup** [alashow/music#4]
![screen shot 2015-01-04 at 12 44 01 am](https://cloud.githubusercontent.com/assets/7024527/5604165/dd98863e-93aa-11e4-8554-ccfa54ecfa36.png)
Hi, sorry to bother again, but it appears the captcha error occurs on your page as well now.
anyway to code a reply?

**Comment by alashow** [comment]
My limit for vk api reached. You need change it, if you need use it.
