### ISSUE TITLE
access token, message error

### ISSUE THREAD

**Issue by nibreh** [alashow/music#5]
Hi

There is a message from VK when I open the url with my APP_Id and client secret

https://oauth.vk.com/authorize?client_id=APP_ID&client_secret=CLIENT_SECRET&scope=audio,offline&response_type=token

Пожалуйста, не копируйте данные из адресной строки для сторонних сайтов. Таким образом Вы можете потерять доступ к Вашему аккаунту. 

Translation (google):
Please do not copy the data from the Address bar to third-party websites. So you can lose access to your account.

Thanks for your help if you know how to resolve this problem

See U

**Comment by alashow** [comment]
hi. It's not  problem. it's just warning message from vk.
