### ISSUE TITLE
My continuation of your work! 

### ISSUE THREAD

**Issue by drpoup** [alashow/music#6]
Hi, once again great work on the app! 

I've worked on some features on my own, and have now just uploaded my work here:
https://github.com/drpoup/vkdl

I was originally planning on it being a fork of your project, but at this point I feel the differences are too great to consolidate it.
If you are really unhappy about this, I can take the repo down and reupload it as a fork.

Once again, good job couldn't have done it without your base code!

**Comment by alashow** [comment]
Hey! Good work!

There no need for fork, that's good now!

Thanks for notifying me :) closing.
