### ISSUE TITLE
Download the full file name (Firefox)

### ISSUE THREAD

**Issue by nibreh** [alashow/music#7]
When downloading, make sure the file is named completely

`artist - song.mp3`

For now, It takes only the first element `artist`.

Maybe because of the interspaces ?

**Comment by alashow** [comment]
Hello!
download.php saves mp3-s as md5-ed audioId, but when serving file to user, it renames filename of downloading mp3 from header, in artist - song.mp3 format.

**Comment by nibreh** [comment]
Hi

You're right, it's working fine, testing with Midori, it renames in artist - song.mp3. 

But with Firefox 41.0.1 (in Elementary OS) it takes only `artist`, and the filename is `artist`. Don't know why. Problem comes from my browser / or OS

Thanks

**Comment by alashow** [comment]
I see problem is with browser, i tested downloading in firefox. I will find fix. Thanks.
