### ISSUE TITLE
How to change the pre defined search on refresh the page?

### ISSUE THREAD

**Issue by cyber-cliff** [alashow/music#9]
I tried this on my local but i cant find where to configure that.

Thanks,

**Comment by nibreh** [comment]
Hi

In `app.js` file, [line 201](https://github.com/alashow/music/blob/master/js/app.js#L201), you can change default music search on refresh.

Now on [line 140](https://github.com/alashow/music/blob/master/index.html#L140) in `index.html`, change `app.min.js` to `app.js`

this is what you want ?

**Comment by alashow** [comment]
@nibreh thanks for answering! Yes, i think it's exact thing what he/she needs.

To disable, just get rid of that if block. To change, just edit artists name string array.

Then minify js or change link to js in index.html.
